# Generated by Django 4.2.3 on 2023-12-26 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0002_alter_vehicle_mileage"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
