# Generated by Django 5.0 on 2023-12-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0003_vehicle_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="work_completed",
            field=models.BooleanField(default=False),
        ),
    ]
