# Generated by Django 5.0 on 2023-12-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apps", "0004_vehicle_work_completed"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="completed_on",
            field=models.DateField(blank=True, null=True),
        ),
    ]
